// All 151 Kanto Pokemon — used by both overlay.html and pokedex.html
// Sprite URLs hit PokeAPI's GitHub-hosted official artwork (free, no auth, no rate limits in practice)
// Types follow Gen 1 typing (Clefairy/Clefable/Jigglypuff/Wigglytuff are Normal, not Fairy)

const TYPE_COLORS = {
  Normal:   { bg: '#A8A878', border: '#6D6D4E', text: '#fff' },
  Fire:     { bg: '#F08030', border: '#9C531F', text: '#fff' },
  Water:    { bg: '#6890F0', border: '#445E9C', text: '#fff' },
  Electric: { bg: '#F8D030', border: '#A1871F', text: '#3a2b00' },
  Grass:    { bg: '#78C850', border: '#4E8234', text: '#fff' },
  Ice:      { bg: '#98D8D8', border: '#638D8D', text: '#1a3a3a' },
  Fighting: { bg: '#C03028', border: '#7D1F1A', text: '#fff' },
  Poison:   { bg: '#A040A0', border: '#682A68', text: '#fff' },
  Ground:   { bg: '#E0C068', border: '#927D44', text: '#3a2a00' },
  Flying:   { bg: '#A890F0', border: '#6D5E9C', text: '#fff' },
  Psychic:  { bg: '#F85888', border: '#A13959', text: '#fff' },
  Bug:      { bg: '#A8B820', border: '#6D7815', text: '#fff' },
  Rock:     { bg: '#B8A038', border: '#786824', text: '#fff' },
  Ghost:    { bg: '#705898', border: '#493963', text: '#fff' },
  Dragon:   { bg: '#7038F8', border: '#4924A1', text: '#fff' },
};

const KANTO_CARDS = [
  { id: 1,   name: 'Bulbasaur',  type: 'Grass',    hp: 60 },
  { id: 2,   name: 'Ivysaur',    type: 'Grass',    hp: 80 },
  { id: 3,   name: 'Venusaur',   type: 'Grass',    hp: 120 },
  { id: 4,   name: 'Charmander', type: 'Fire',     hp: 50 },
  { id: 5,   name: 'Charmeleon', type: 'Fire',     hp: 80 },
  { id: 6,   name: 'Charizard',  type: 'Fire',     hp: 150 },
  { id: 7,   name: 'Squirtle',   type: 'Water',    hp: 60 },
  { id: 8,   name: 'Wartortle',  type: 'Water',    hp: 80 },
  { id: 9,   name: 'Blastoise',  type: 'Water',    hp: 130 },
  { id: 10,  name: 'Caterpie',   type: 'Bug',      hp: 40 },
  { id: 11,  name: 'Metapod',    type: 'Bug',      hp: 70 },
  { id: 12,  name: 'Butterfree', type: 'Bug',      hp: 80 },
  { id: 13,  name: 'Weedle',     type: 'Bug',      hp: 40 },
  { id: 14,  name: 'Kakuna',     type: 'Bug',      hp: 70 },
  { id: 15,  name: 'Beedrill',   type: 'Bug',      hp: 80 },
  { id: 16,  name: 'Pidgey',     type: 'Normal',   hp: 50 },
  { id: 17,  name: 'Pidgeotto',  type: 'Normal',   hp: 70 },
  { id: 18,  name: 'Pidgeot',    type: 'Normal',   hp: 100 },
  { id: 19,  name: 'Rattata',    type: 'Normal',   hp: 40 },
  { id: 20,  name: 'Raticate',   type: 'Normal',   hp: 70 },
  { id: 21,  name: 'Spearow',    type: 'Normal',   hp: 50 },
  { id: 22,  name: 'Fearow',     type: 'Normal',   hp: 90 },
  { id: 23,  name: 'Ekans',      type: 'Poison',   hp: 50 },
  { id: 24,  name: 'Arbok',      type: 'Poison',   hp: 90 },
  { id: 25,  name: 'Pikachu',    type: 'Electric', hp: 60 },
  { id: 26,  name: 'Raichu',     type: 'Electric', hp: 100 },
  { id: 27,  name: 'Sandshrew',  type: 'Ground',   hp: 60 },
  { id: 28,  name: 'Sandslash',  type: 'Ground',   hp: 90 },
  { id: 29,  name: 'Nidoran♀', type: 'Poison', hp: 50, slug: 'nidoran-f' },
  { id: 30,  name: 'Nidorina',   type: 'Poison',   hp: 70 },
  { id: 31,  name: 'Nidoqueen',  type: 'Poison',   hp: 110 },
  { id: 32,  name: 'Nidoran♂', type: 'Poison', hp: 50, slug: 'nidoran-m' },
  { id: 33,  name: 'Nidorino',   type: 'Poison',   hp: 70 },
  { id: 34,  name: 'Nidoking',   type: 'Poison',   hp: 110 },
  { id: 35,  name: 'Clefairy',   type: 'Normal',   hp: 60 },
  { id: 36,  name: 'Clefable',   type: 'Normal',   hp: 90 },
  { id: 37,  name: 'Vulpix',     type: 'Fire',     hp: 50 },
  { id: 38,  name: 'Ninetales',  type: 'Fire',     hp: 90 },
  { id: 39,  name: 'Jigglypuff', type: 'Normal',   hp: 60 },
  { id: 40,  name: 'Wigglytuff', type: 'Normal',   hp: 90 },
  { id: 41,  name: 'Zubat',      type: 'Poison',   hp: 50 },
  { id: 42,  name: 'Golbat',     type: 'Poison',   hp: 80 },
  { id: 43,  name: 'Oddish',     type: 'Grass',    hp: 50 },
  { id: 44,  name: 'Gloom',      type: 'Grass',    hp: 70 },
  { id: 45,  name: 'Vileplume',  type: 'Grass',    hp: 100 },
  { id: 46,  name: 'Paras',      type: 'Bug',      hp: 50 },
  { id: 47,  name: 'Parasect',   type: 'Bug',      hp: 80 },
  { id: 48,  name: 'Venonat',    type: 'Bug',      hp: 60 },
  { id: 49,  name: 'Venomoth',   type: 'Bug',      hp: 80 },
  { id: 50,  name: 'Diglett',    type: 'Ground',   hp: 30 },
  { id: 51,  name: 'Dugtrio',    type: 'Ground',   hp: 70 },
  { id: 52,  name: 'Meowth',     type: 'Normal',   hp: 50 },
  { id: 53,  name: 'Persian',    type: 'Normal',   hp: 80 },
  { id: 54,  name: 'Psyduck',    type: 'Water',    hp: 60 },
  { id: 55,  name: 'Golduck',    type: 'Water',    hp: 90 },
  { id: 56,  name: 'Mankey',     type: 'Fighting', hp: 50 },
  { id: 57,  name: 'Primeape',   type: 'Fighting', hp: 80 },
  { id: 58,  name: 'Growlithe',  type: 'Fire',     hp: 60 },
  { id: 59,  name: 'Arcanine',   type: 'Fire',     hp: 110 },
  { id: 60,  name: 'Poliwag',    type: 'Water',    hp: 50 },
  { id: 61,  name: 'Poliwhirl',  type: 'Water',    hp: 70 },
  { id: 62,  name: 'Poliwrath',  type: 'Water',    hp: 100 },
  { id: 63,  name: 'Abra',       type: 'Psychic',  hp: 30 },
  { id: 64,  name: 'Kadabra',    type: 'Psychic',  hp: 60 },
  { id: 65,  name: 'Alakazam',   type: 'Psychic',  hp: 90 },
  { id: 66,  name: 'Machop',     type: 'Fighting', hp: 60 },
  { id: 67,  name: 'Machoke',    type: 'Fighting', hp: 90 },
  { id: 68,  name: 'Machamp',    type: 'Fighting', hp: 120 },
  { id: 69,  name: 'Bellsprout', type: 'Grass',    hp: 50 },
  { id: 70,  name: 'Weepinbell', type: 'Grass',    hp: 70 },
  { id: 71,  name: 'Victreebel', type: 'Grass',    hp: 100 },
  { id: 72,  name: 'Tentacool',  type: 'Water',    hp: 50 },
  { id: 73,  name: 'Tentacruel', type: 'Water',    hp: 90 },
  { id: 74,  name: 'Geodude',    type: 'Rock',     hp: 50 },
  { id: 75,  name: 'Graveler',   type: 'Rock',     hp: 80 },
  { id: 76,  name: 'Golem',      type: 'Rock',     hp: 110 },
  { id: 77,  name: 'Ponyta',     type: 'Fire',     hp: 60 },
  { id: 78,  name: 'Rapidash',   type: 'Fire',     hp: 90 },
  { id: 79,  name: 'Slowpoke',   type: 'Water',    hp: 60 },
  { id: 80,  name: 'Slowbro',    type: 'Water',    hp: 100 },
  { id: 81,  name: 'Magnemite',  type: 'Electric', hp: 40 },
  { id: 82,  name: 'Magneton',   type: 'Electric', hp: 80 },
  { id: 83,  name: 'Farfetch’d', type: 'Normal', hp: 60, slug: 'farfetchd' },
  { id: 84,  name: 'Doduo',      type: 'Normal',   hp: 50 },
  { id: 85,  name: 'Dodrio',     type: 'Normal',   hp: 80 },
  { id: 86,  name: 'Seel',       type: 'Water',    hp: 60 },
  { id: 87,  name: 'Dewgong',    type: 'Water',    hp: 90 },
  { id: 88,  name: 'Grimer',     type: 'Poison',   hp: 70 },
  { id: 89,  name: 'Muk',        type: 'Poison',   hp: 100 },
  { id: 90,  name: 'Shellder',   type: 'Water',    hp: 40 },
  { id: 91,  name: 'Cloyster',   type: 'Water',    hp: 70 },
  { id: 92,  name: 'Gastly',     type: 'Ghost',    hp: 40 },
  { id: 93,  name: 'Haunter',    type: 'Ghost',    hp: 60 },
  { id: 94,  name: 'Gengar',     type: 'Ghost',    hp: 90 },
  { id: 95,  name: 'Onix',       type: 'Rock',     hp: 90 },
  { id: 96,  name: 'Drowzee',    type: 'Psychic',  hp: 60 },
  { id: 97,  name: 'Hypno',      type: 'Psychic',  hp: 90 },
  { id: 98,  name: 'Krabby',     type: 'Water',    hp: 50 },
  { id: 99,  name: 'Kingler',    type: 'Water',    hp: 90 },
  { id: 100, name: 'Voltorb',    type: 'Electric', hp: 40 },
  { id: 101, name: 'Electrode',  type: 'Electric', hp: 70 },
  { id: 102, name: 'Exeggcute',  type: 'Grass',    hp: 60 },
  { id: 103, name: 'Exeggutor',  type: 'Grass',    hp: 100 },
  { id: 104, name: 'Cubone',     type: 'Ground',   hp: 50 },
  { id: 105, name: 'Marowak',    type: 'Ground',   hp: 80 },
  { id: 106, name: 'Hitmonlee',  type: 'Fighting', hp: 80 },
  { id: 107, name: 'Hitmonchan', type: 'Fighting', hp: 80 },
  { id: 108, name: 'Lickitung',  type: 'Normal',   hp: 90 },
  { id: 109, name: 'Koffing',    type: 'Poison',   hp: 50 },
  { id: 110, name: 'Weezing',    type: 'Poison',   hp: 80 },
  { id: 111, name: 'Rhyhorn',    type: 'Ground',   hp: 70 },
  { id: 112, name: 'Rhydon',     type: 'Ground',   hp: 110 },
  { id: 113, name: 'Chansey',    type: 'Normal',   hp: 130 },
  { id: 114, name: 'Tangela',    type: 'Grass',    hp: 70 },
  { id: 115, name: 'Kangaskhan', type: 'Normal',   hp: 100 },
  { id: 116, name: 'Horsea',     type: 'Water',    hp: 40 },
  { id: 117, name: 'Seadra',     type: 'Water',    hp: 70 },
  { id: 118, name: 'Goldeen',    type: 'Water',    hp: 50 },
  { id: 119, name: 'Seaking',    type: 'Water',    hp: 80 },
  { id: 120, name: 'Staryu',     type: 'Water',    hp: 50 },
  { id: 121, name: 'Starmie',    type: 'Water',    hp: 80 },
  { id: 122, name: 'Mr. Mime',   type: 'Psychic',  hp: 60, slug: 'mr-mime' },
  { id: 123, name: 'Scyther',    type: 'Bug',      hp: 80 },
  { id: 124, name: 'Jynx',       type: 'Ice',      hp: 80 },
  { id: 125, name: 'Electabuzz', type: 'Electric', hp: 80 },
  { id: 126, name: 'Magmar',     type: 'Fire',     hp: 80 },
  { id: 127, name: 'Pinsir',     type: 'Bug',      hp: 80 },
  { id: 128, name: 'Tauros',     type: 'Normal',   hp: 90 },
  { id: 129, name: 'Magikarp',   type: 'Water',    hp: 30 },
  { id: 130, name: 'Gyarados',   type: 'Water',    hp: 110 },
  { id: 131, name: 'Lapras',     type: 'Water',    hp: 100 },
  { id: 132, name: 'Ditto',      type: 'Normal',   hp: 60 },
  { id: 133, name: 'Eevee',      type: 'Normal',   hp: 60 },
  { id: 134, name: 'Vaporeon',   type: 'Water',    hp: 90 },
  { id: 135, name: 'Jolteon',    type: 'Electric', hp: 80 },
  { id: 136, name: 'Flareon',    type: 'Fire',     hp: 90 },
  { id: 137, name: 'Porygon',    type: 'Normal',   hp: 70 },
  { id: 138, name: 'Omanyte',    type: 'Rock',     hp: 50 },
  { id: 139, name: 'Omastar',    type: 'Rock',     hp: 90 },
  { id: 140, name: 'Kabuto',     type: 'Rock',     hp: 50 },
  { id: 141, name: 'Kabutops',   type: 'Rock',     hp: 90 },
  { id: 142, name: 'Aerodactyl', type: 'Rock',     hp: 100 },
  { id: 143, name: 'Snorlax',    type: 'Normal',   hp: 150 },
  { id: 144, name: 'Articuno',   type: 'Ice',      hp: 120 },
  { id: 145, name: 'Zapdos',     type: 'Electric', hp: 120 },
  { id: 146, name: 'Moltres',    type: 'Fire',     hp: 120 },
  { id: 147, name: 'Dratini',    type: 'Dragon',   hp: 50 },
  { id: 148, name: 'Dragonair',  type: 'Dragon',   hp: 80 },
  { id: 149, name: 'Dragonite',  type: 'Dragon',   hp: 130 },
  { id: 150, name: 'Mewtwo',     type: 'Psychic',  hp: 150 },
  { id: 151, name: 'Mew',        type: 'Psychic',  hp: 100 },
];

// Returns { standard, shiny } URLs for a card id
function cardSprites(id) {
  const base = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork';
  return {
    standard: `${base}/${id}.png`,
    shiny:    `${base}/shiny/${id}.png`,
  };
}

// Expose for browser global use
if (typeof window !== 'undefined') {
  window.KANTO_CARDS = KANTO_CARDS;
  window.TYPE_COLORS = TYPE_COLORS;
  window.cardSprites = cardSprites;
}
